language: python
sudo: false
cache:
  pip: true
python:
- '2.7'
install:
- pip install six
- pip install -U -r requirements.txt
- pip install codacy-coverage
script:
- invoke test
- echo "finished running tests on repo"
- echo " now deploy core lambda pacakges"
- if [ "$TRAVIS_BRANCH" = "production" ]; then echo "Test succeeded! PUBLISHING LAMBDAs";
  invoke deploy all; fi
after_success:
- python-codacy-coverage -r coverage.xml
