region: us-east-1

function_name: trigger_staging_build 
handler: service.handler
role: lambda_s3_step_function 
description: trigger the process of building an envrionment and staging things 

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id:
aws_secret_access_key:

# dist_directory: dist
timeout: 60 
memory_size: 128 
