region: us-east-1

function_name: update-bs-config
handler: service.handler
role: sysadmin
description: Update the configuration template of an EB environment. Sets waitfor_details in event JSON.

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id:
aws_secret_access_key:

# dist_directory: dist
timeout: 300
memory_size: 256
